### PR TITLE
added the api for searching books

### PR DESCRIPTION
**Pull request by syedfahdali**
I have added the fetch method for the Book API.

### CODE REVIEW

**Comment by syedfahdali** [comment]
I have done folder structuring and unification of search,description,threads  with the home page 
Note: Please merge this pull request as this will make things less confusing 
Annotation 2024-10-25 125112

**Comment by syedfahdali** [comment]
Annotation 2024-10-25 125803

**Comment by syedfahdali** [comment]
final image

**Comment by madnansultandotme** [comment]
It is causing conflict resolve and merge it back

**Pull request closed without merging**
